GET http://{{baseurl}}/developer/v3/document/tips
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

###

GET http://{{baseurl}}/developer/v3/document/statuses
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

###

GET http://{{baseurl}}/developer/v3/document/info
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

{
    "number": "62-0524/2024",
    "id": 0
}

###

GET http://{{baseurl}}/developer/v3/document/list
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

{
	"clid": 1839
}

###

POST http://{{baseurl}}/developer/v3/document/add
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

{
    "did": 962,
	"dateStart": "2024-07-01",
	"dateEnd": "2024-12-31",
	"description": "Описание договора",
    "mcid": 1,
    "idtype": 1,
    "template": 19,
	"status": 1
}

###

POST http://{{baseurl}}/developer/v3/document/update
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

{
    "id": 536,
    "title": "Договор через API",
	"description": "Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона",
	"dateStart": "2024-07-02",
	"dateEnd": "2024-09-31",
	"mcid": 2,
	"idtype": 1,
	"template": 28,
	"status": 1
}

###

POST http://{{baseurl}}/developer/v3/document/status.change
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

{
	"id": 536,
	"description": "Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться",
	"status": 3
}

###

POST http://{{baseurl}}/developer/v3/document/mail
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

{
	"id": 536,
	"status": 5
}

###

POST http://{{baseurl}}/developer/v3/document/delete
Content-Type: application/json
apikey: {{token}}
login: vladislav@isaler.ru

{
	"id": 536
}

###